import { logger, PromiseExecutor } from '@nx/devkit';
import { TestDevcontainerFeatureExecutorSchema } from './schema';
import { ProjectUtils } from '@ebizbase/nx-devkit';
import { execFileSync } from 'child_process';

const runExecutor: PromiseExecutor<TestDevcontainerFeatureExecutorSchema> = async (options, context) => {
  let projectUtils;
  try {
    projectUtils = new ProjectUtils(context);
  } catch (error: unknown) {
    logger.fatal('No project name provided', error);
    return { success: false };
  }
  const commands = ['npx', 'devcontainer', 'features', 'test','--skip-autogenerated', '-p', projectUtils.getProjectRoot(), '-f', projectUtils.getProjectName(), '-i', 'debian:bookworm-slim'];
  if (options.filter) {
    commands.push('--filter', options.filter);
  }
  execFileSync(commands[0], commands.slice(1), { cwd: context.root, stdio: 'inherit' });

  return { success: true };
};

export default runExecutor;
